Implement memoize
checkdigit/memoize pull request #2
Opened 2023-06-09 18:08 UTC by greg-w101

2023-06-12 18:05 UTC, carlansley requested changes

2023-06-12 18:05 UTC, carlansley commented on .github/workflows/ci.yml
> -      - name: Run Tests
we should be running tests

2023-06-12 18:05 UTC, carlansley commented on .github/workflows/ci.yml
> -      - name: Run Tests
we should be running tests

2023-06-12 18:05 UTC, carlansley commented on LICENSE.txt
> +Copyright (c) 2021-2023 Check Digit, LLC
this is a new repo, should just be 2023

2023-06-12 18:05 UTC, carlansley commented on README.md
> +Copyright (c) 2021-2023 [Check Digit, LLC](https://checkdigit.com)
2023

2023-06-12 18:05 UTC, carlansley commented on README.md
> +Memoize is a light-weight utility library used by Check Digit services for memoization purposes.
I think we should add an explantation that its designed to memoize promises, and evict from the cache anything that rejects.

2023-06-12 18:05 UTC, carlansley commented on package.json
> +  "description": "Memoize is a light-weight utility library used by Check Digit services for memoization purposes",
...for memoizing promises with cache eviction on reject

2023-06-12 18:05 UTC, carlansley commented on src/index.ts
> + * Copyright (c) 2021-2023 Check Digit, LLC
2023

2023-06-12 18:05 UTC, carlansley commented on src/memoize.spec.ts
> + * Copyright (c) 2021-2023 Check Digit, LLC
2023

2023-06-12 18:05 UTC, carlansley commented on src/memoize.spec.ts
> +import memoize from './memoize';
I think it should import memoize from `index.ts`, for complete code coverage

2023-06-12 18:05 UTC, carlansley commented on src/memoize.ts
> + * Copyright (c) 2021-2023 Check Digit, LLC
2023

2023-06-12 18:05 UTC, carlansley commented on src/memoize.ts
> + * Memoize an async function.  The promise is cached, not the value.  This guarantees the underlying function is
a version of this comment probably should be in the README

2023-06-13 18:20 UTC, lukebrdn approved these changes, later dismissed
lgtm

2023-06-14 21:10 UTC, carlansley requested changes

2023-06-14 21:10 UTC, carlansley commented on README.md
> +Memoize is a small async function used by Check Digit services for memoizing promises with cache eviction on reject.
remove the "used by Check Digit services"

2023-06-14 21:10 UTC, carlansley commented on README.md
> +import { memoize } from '@checkdigit/memoize';
I don't think this code would work, there's only a default import.   believe should be `import memoize from '@checkdigit/memoize';`

2023-06-15 17:19 UTC, greg-w101 commented
> lgtm

Luke you left a comment instead of approving haha

2023-06-20 15:04 UTC, lukebrdn approved these changes
lgtm

2023-06-22 18:03 UTC, carlansley approved these changes

2023-06-22 19:35 UTC, merged