Make sure object key order doesn't affect caching
checkdigit/memoize pull request #4
Opened 2023-08-03 20:00 UTC by carlansley

Fixes #3

2023-08-04 17:50 UTC, carlansley commented
fyi @ramaghanta I removed the unnecessary strategy/matrix sections of some of the actions to simplify our management of the branch protection rules.  The specific node version isn't in the name now, so we don't have to update e.g. the Publish rule just because of a new version of node.

2023-08-04 18:06 UTC, ramaghanta commented
> fyi @ramaghanta I removed the unnecessary strategy/matrix sections of some of the actions to simplify our management of the branch protection rules. The specific node version isn't in the name now, so we don't have to update e.g. the Publish rule just because of a new version of node.

sounds good. please update the Node 18 migration document with these new actions.

2023-08-04 18:08 UTC, carlansley commented
> > fyi @ramaghanta I removed the unnecessary strategy/matrix sections of some of the actions to simplify our management of the branch protection rules. The specific node version isn't in the name now, so we don't have to update e.g. the Publish rule just because of a new version of node.
> 
> sounds good. please update the Node 18 migration document with these new actions.

I will, assuming all goes well with this one (and maybe the next one or two).  Just in case issues crop up.

2023-08-04 18:10 UTC, ramaghanta approved these changes, later dismissed
lgtm

2023-08-04 20:30 UTC, carlansley commented
@ramaghanta sorry to do this to you, but I realized there were a bunch of edge cases we're not handling correctly.

2023-08-07 14:35 UTC, ramaghanta approved these changes, later dismissed
lgtm

2023-08-07 21:20 UTC, le-cong requested changes
just a few comments

2023-08-07 21:20 UTC, le-cong commented on src/memoize.ts
> +        cache.delete(cacheKey);
it's probably not an issue, just want to make sure that we are ok in case a value could be rejected but somehow gets returned from the catch because the following call is close enough to the initial call before the rejection happens? one use case I can think of is when using 'retry+timeout' where it hopes the next try of the same function call to be successful. in another words, it may take long time for a slow running process to be rejected and open up for a fresh start.

2023-08-07 21:20 UTC, le-cong commented on src/memoize.ts
> +        case 'object': {
should we do sth about Set/Map since they will become "{}" no matter the contents unless a customized serializer is provided

2023-08-07 21:20 UTC, le-cong commented on src/memoize.spec.ts
> +    assert.deepEqual(await promise3, '[{"b":1,"a":2},{"b":{"y":"b","x":"a"},"a":1},{"b":2,"a":[2,1],"c":3},2]');
replace `deepEqual` with `equal` for string comparison?

2023-08-09 18:11 UTC, carlansley commented on src/memoize.ts
> +        cache.delete(cacheKey);
discussed with @le-cong, we agreed there's not much we can do about this situation.  long running promises shouldn't use memoize (or really any kind of caching) for this reason.

2023-08-10 18:36 UTC, carlansley commented on src/memoize.ts
> +        case 'object': {
I'm now checking for objects that don't have the null prototype, so should error on anything that isn't effectively an object literal

2023-08-10 19:27 UTC, greg-w101 approved these changes
lgtm

2023-08-10 23:43 UTC, le-cong approved these changes

2023-08-11 13:53 UTC, ramaghanta approved these changes

2023-08-11 14:15 UTC, merged