Update to Node 20 and latest dependencies + ESM only
checkdigit/memoize pull request #9
Opened 2024-03-27 19:22 UTC by carlansley

2024-03-28 14:17 UTC, ramaghanta requested changes

2024-03-28 14:17 UTC, ramaghanta commented on package.json
> +    "node": ">=20.11"
`"type": "module",` and `"sideEffects": false,`

2024-04-01 14:33 UTC, ramaghanta approved these changes
lgtm

2024-04-02 14:58 UTC, greg-w101 approved these changes
lgtm

2024-04-02 16:53 UTC, merged